name: Cleanup

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 */14 * *' # every 14 days

jobs:
  cleanup-updater:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        suite:
        - { ecosystem: bundler }
        - { ecosystem: cargo }
        - { ecosystem: composer }
        - { ecosystem: docker }
        - { ecosystem: elm }
        - { ecosystem: gitsubmodule }
        - { ecosystem: github-actions }
        - { ecosystem: gomod }
        - { ecosystem: gradle }
        - { ecosystem: mix }
        - { ecosystem: maven }
        - { ecosystem: npm }
        - { ecosystem: nuget }
        - { ecosystem: pub }
        - { ecosystem: pip }
        # TODO: restore swift here once supported elsewhere
        # - { ecosystem: swift }
        - { ecosystem: terraform }

    steps:
    - name: Delete old dependabot-updater-${{ matrix.suite.ecosystem }} images
      uses: actions/delete-package-versions@v4
      with:
        package-name: 'dependabot-updater-${{ matrix.suite.ecosystem }}'
        package-type: 'container'
        min-versions-to-keep: 20
        delete-only-pre-release-versions: "true"

  cleanup-server:
    runs-on: ubuntu-latest

    steps:
    - name: Delete old dependabot-server images
      uses: actions/delete-package-versions@v4
      with:
        package-name: 'dependabot-server'
        package-type: 'container'
        min-versions-to-keep: 20
        delete-only-pre-release-versions: "true"
