name: Extensions

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: ['extensions-*']
    paths:
      - 'extensions/**'
      - '.github/workflows/extensions.yml'
  pull_request:
    branches: [main]
    paths:
      - 'extensions/**'
      - '.github/workflows/extensions.yml'

permissions:
  contents: write # write required for ncipollo/release-action to create a release
  attestations: write # required for actions/attest-build-provenance
  id-token: write # required for actions/attest-build-provenance

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # wait for previous runs to complete on main and tags
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/') }}

jobs:
  Azure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup turborepo caching
        uses: rharkor/caching-for-turbo@v1.8

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Download deps
        run: pnpm install
        working-directory: '${{ github.workspace }}/extensions/azure'

      - name: Build
        run: pnpm dlx turbo build
        working-directory: '${{ github.workspace }}/extensions/azure'

      - name: Lint
        run: pnpm dlx turbo lint
        working-directory: '${{ github.workspace }}/extensions/azure'

      - name: Test
        run: pnpm dlx turbo test
        working-directory: '${{ github.workspace }}/extensions/azure'

      - name: Create Extension
        run: >
          pnpm tfx extension create
          --manifest-globs vss-extension.json
          --output-path ${{ github.workspace }}/out
          --json5
          ${{ (!startsWith(github.ref, 'refs/tags/') && '--overrides-file overrides.dev.json') || '' }}
        working-directory: extensions/azure

      - name: Upload Artifact (extensions-azure)
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}/out/*
          name: extensions-azure

      - name: Provenance Attestation
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: ${{ github.workspace }}/out/*.vsix

      - name: Upload Release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: '${{ github.workspace }}/out/*.vsix'
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          allowUpdates: true

      - name: Publish to marketplace
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
        run: >
          pnpm tfx extension publish
          --vsix ${{ github.workspace }}/out/*.vsix
          --auth-type pat
          --token ${{ secrets.AZURE_DEVOPS_EXTENSION_TOKEN }}
          ${{ (github.ref == 'refs/heads/main' && '--share-with tingle rhyskoedijk') || '' }}

  # Bitbucket:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup turborepo caching
  #       uses: rharkor/caching-for-turbo@v1.8

  #     - name: Setup pnpm
  #       uses: pnpm/action-setup@v4

  #     - name: Setup node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 22
  #         cache: pnpm

  #     - name: Download deps
  #       run: pnpm install
  #       working-directory: '${{ github.workspace }}/extensions/bitbucket'
